{% set name = "mpiplus" %}
{% set version = "v0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5f051210b8cd321fdcbfa97a6e1606b63e6d6c7214c393bc04f93a8545b6d3a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.11

test:
  requires:
    - pytest
    - coverage >=4.4
    - mpi4py
  imports:
    - mpiplus

about:
  home: http://github.com/choderalab/mpiplus
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Utilities to run on MPI'

  description: |
    Mpiplus is a GPU-accelerated Python framework for exploring 
    algorithms for alchemical free energy calculations
  doc_url: http://mpiplus.readthedocs.io/
  dev_url: https://github.com/choderalab/mpiplus

extra:
  recipe-maintainers:
    - ijpulidos
    - mikemhenry
    - jchodera
