# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WHIpJueyUHCq2t3/sOj5rPj4DXR4L7TdELgzqtzHAZ1XQxzkfZ1084yNSRNeKPJxxTuYlWFI7FCU3xNIvxqt39e/YCFh8lHGt+DmwS6MKiA6YajrO8GlkvgRGstxYjAxUNFpnacvRBheEdemljpVkd4dvjWVmiZpY3rY3x2LcbHGFDvfSOTd2m7c3Tt0BvBTZByi2I7DMTXm+g8asz7qg/Y7xatz+L1t2g3H/8kAhlGlC3R05SLb+YHgUGlnCVu7NGigpqvs4+NKaH1AzYbmi6QFyCZ+MPeBjG8B6+ItIzeRwu+XLEu/nEy2GHI//2Bcwy5RsRiMmgxeVyjD7IiGjZ979d5pYPQrJGYhzlrNZjE4KuN3HEyx358OvUBzsraE5fZkOu+MBvaL5iLiZ0k2NX348z2DsGZlR4aIdJaM2Ye27+5iPy/QTmH+7KLhGk3uQEFDxVBCL1EMP6rvId48Mh3MfQgjEq+R84j4SeoM6cDTtoEVA3vX4xO+E2swodTlr2a6FDNKWBLh4KZqclI/YZ48rfadSjY1fMz/4Wfts1teUAjaB64PoJ1FZm9vdbnFcNyLJtASjC+u5SRA2i1Rugruxpjz0hu11Amxc/lDI6AEVwYS1V7SW/MgWh2oi069MPtA+SeQfFY/fpqo7coTbzgSnGNztmMzkKboQaPlmZo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
